### ISSUE TITLE
Crash when loading module

### ISSUE THREAD

**Issue by Jolt151** [LSPosed/DisableFlagSecure#24]
Device is a OnePlus CPH2451 running Android 13

```
----part 1 start----
[ 2023-12-06T11:09:36.189     1000:  3193:  3193 I/LSPosed-Bridge  ] Loading legacy module io.github.lsposed.disableflagsecure from /data/app/~~np-RhLVwfUpIcXjJgiX9YQ==/io.github.lsposed.disableflagsecure-m7Cn2mAAWhTmf4d9jPoTvw==/base.apk
[ 2023-12-06T11:09:36.192     1000:  3193:  3193 I/LSPosed-Bridge  ]   Loading class io.github.lsposed.disableflagsecure.DisableFlagSecure
[ 2023-12-06T11:09:36.892     1000:  3193:  3193 E/LSPosed-Bridge  ] DoXjnuiTAVJ.T.Tbz.Iuyo.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.wm.WindowManagerServiceImpl
	at DoXjnuiTAVJ.T.Tbz.Iuyo.XposedHelpers.findClass(Unknown Source:12)
	at io.github.lsposed.disableflagsecure.DisableFlagSecure.handleLoadPackage(Unknown Source:291)
	at DoXjnuiTAVJ.T.Tbz.Iuyo.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at DoXjnuiTAVJ.T.Tbz.Iuyo.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at DoXjnuiTAVJ.T.Tbz.Iuyo.callbacks.XCallback.callAll(Unknown Source:26)
	at H0.a(Unknown Source:30)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:123)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at [com.android.server.SystemServer.run(SystemServer.java:1011)](http://com.android.server.systemserver.run(systemserver.java:1011)/)
	at [com.android.server.SystemServer.main(SystemServer.java:669)](http://com.android.server.systemserver.main(systemserver.java:669)/)
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)](http://com.android.internal.os.runtimeinit$methodandargscaller.run(runtimeinit.java:584)/)
	at [com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)](http://com.android.internal.os.zygoteinit.main(zygoteinit.java:991)/)
Caused by: java.lang.ClassNotFoundException: com.android.server.wm.WindowManagerServiceImpl
	at java.lang.Class.classForName(Native Method)
	at [java.lang.Class.forName(Class.java:536)](http://java.lang.class.forname(class.java:536)/)
	at q.a(Unknown Source:16)
	at DoXjnuiTAVJ.T.Tbz.Iuyo.XposedHelpers.findClass(Unknown Source:4)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.android.server.wm.WindowManagerServiceImpl
	... 17 more
[ 2023-12-06T11:11:58.909    10412: 23370: 23370 I/LSPosed-Bridge  ] Loading legacy module io.github.lsposed.disableflagsecure from /data/app/~~np-RhLVwfUpIcXjJgiX9YQ==/io.github.lsposed.disableflagsecure-m7Cn2mAAWhTmf4d9jPoTvw==/base.apk
[ 2023-12-06T11:11:58.910    10412: 23370: 23370 I/LSPosed-Bridge  ]   Loading class io.github.lsposed.disableflagsecure.DisableFlagSecure
```

**Comment by Jolt151** [comment]
@JasonKhew96 Is there any reason why this is a wontfix?

**Comment by JasonKhew96** [comment]
> @JasonKhew96 Is there any reason why this is a wontfix?

this is not a crash log, you can ignore this error

**Comment by Jolt151** [comment]
Ah, thanks. The module is not working for me so I'm trying to debug and see what the root cause is. Will deploy the app locally and debug next.

**Comment by VD171** [comment]
Apparentely, the class "com.android.server.wm.WindowManagerServiceImpl" does not exist, at the moment.

**Comment by JasonKhew96** [comment]
> Apparentely, the class "com.android.server.wm.WindowManagerServiceImpl" does not exist, at the moment.

it's HyperOS things https://github.com/LSPosed/DisableFlagSecure/pull/22
